name: cron job
on:
  schedule:
    - cron: "15 7 * * *" # daily at 7:15 AM UTC
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: call endpoint to keep database alive
        run: |
          curl --request PUT \
            --url '${{ secrets.SITE_URL }}/api/keep-alive' \
            --header 'x-keep-alive-api-secret: ${{ secrets.KEEP_ALIVE_API_SECRET }}'
